---
title: "Final Project"
author: "David Nemirovsky & Jared Klug"
output: github_document
date: 5/13/21
--- 

```{r setup, include = FALSE}
library(tidyverse)
library(caret)
library(ISLR)
library(e1071)
library(gtsummary)
library(vip)
library(patchwork)
library(ranger)
library(gbm)
library(pROC)
library(visdat)
library(kernlab)
library(DALEX)
library(pdp)
library(lime)

knitr::opts_chunk$set(
  fig.align = "center",
  fig.width = 7,
  fig.asp = .6,
  out.width = "100%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(37564)
```

## **EDA**

```{r eda, message = F, warning = F}
titanic_df = 
  read_csv("./data/train.csv") %>% 
  janitor::clean_names() %>% 
  mutate(survived = fct_recode(as.factor(survived), yes = "1", no = "0"), 
         survived = fct_relevel(survived, "yes", "no"),
         pclass = as.factor(pclass), 
         sex = as.factor(sex), 
         embarked = as.factor(embarked)) %>% 
  select(-c(ticket, cabin, name, passenger_id))

# Missing Data EDA:
vis_miss(titanic_df)

titanic_df %>% 
  ggplot(aes(x = age, fill = survived)) +
  geom_density(alpha = 0.75)

# Missing Survivals:
titanic_df %>% 
  filter(is.na(age)) %>% 
  group_by(survived) %>% 
  summarise(count = n())

# All survivals:
titanic_df %>% 
  group_by(survived) %>% 
  summarise(count = n())

# Survival percentage in NAs is similar to actual survival rate so assume missingness is not related to outcome -> MAR.

# Bagging imputation will be used to fill in missing age data, embarked will be replaced by the most popular port "S":

titanic_df %>% 
  group_by(embarked) %>% 
  summarise(count = n())

titanic_df[is.na(titanic_df$embarked),"embarked"] = "S"

trainX = titanic_df[-1]
train_bag = preProcess(trainX, method = "bagImpute")
train_imp = predict(train_bag, trainX)
train_df = cbind(titanic_df[1], train_imp)

# Descriptive Summary Table:
eda_df = 
  train_df %>% 
  mutate(survived = fct_recode(as.factor(survived), 
                            Survived = "yes", Died = "no"), 
         sex = fct_recode(as.factor(sex), 
                            Female = "female", Male = "male"), 
         embarked = fct_recode(as.factor(embarked), 
                               Cherbourg = "C", 
                               Queenstown = "Q", 
                               Southampton = "S"), 
         pclass = fct_recode(as.factor(pclass), 
                             Upper = "1", 
                             Middle = "2", 
                             Lower = "3"))
eda_df %>% 
  tbl_summary(by = survived, 
              label = 
                list(
                  pclass ~ "Socioeconomic Status",
                  sex ~ "Sex",
                  age ~ "Age",
                  sib_sp ~ "Number of Siblings/Spouse on Board",
                  parch ~ "Number of Parents/Children on Board",
                  fare ~ "Passenger Fare", 
                  embarked ~ "Port of Embarkation")) %>% 
  add_overall

#featurePlot(x = select(mutate(train_df, 
#                              pclass = as.numeric(pclass), 
#                              sex = as.numeric(sex),
#                              embarked = as.numeric(embarked)),
#                       pclass:embarked), 
#            y = train_df$survived,
#            scales = list(x = list(relation = "free"), 
#                          y = list(relation = "free")),
#            plot = "density", 
#            auto.key = list(columns = 2))

eda_df %>% 
  ggplot(aes(x = fare)) + 
  geom_density()

eda_df %>% 
  ggplot(aes(x = sib_sp)) + 
  geom_density()

eda_df %>% 
  ggplot(aes(x = parch)) + 
  geom_density()

# Survival by Age:
plot_age = 
  eda_df %>% 
  ggplot(aes(x = age, fill = survived)) +
  geom_density(alpha = 0.75) +
  labs(x = "Age", y = "Density") +
  scale_fill_discrete(name = "Survived")

# Survival by Fare:
plot_fare = 
  eda_df %>% 
  filter(fare < 100) %>% 
  ggplot(aes(x = fare, fill = survived)) +
  geom_density(alpha = 0.75) +
  labs(x = "Fare", y = "Density") +
  scale_fill_discrete(name = "Survived")

# Survival by Number of Siblings/Spouse:
plot_sibsp = 
  eda_df %>% 
  filter(sib_sp < 5) %>% 
  ggplot(aes(x = sib_sp, fill = survived)) +
  geom_density(alpha = 0.75) +
  labs(x = "Number of Siblings/Spouse", y = "Density") +
  scale_fill_discrete(name = "Survived")

# Survival by Number of Parents/Children:
plot_parch = 
  eda_df %>% 
  filter(parch < 4) %>% 
  ggplot(aes(x = parch, fill = survived)) +
  geom_density(alpha = 0.75) +
  labs(x = "Number of Parents/Children", y = "Density") +
  scale_fill_discrete(name = "Survived")

# Survival by Sex:
plot_sex = 
  eda_df %>% 
  ggplot(aes(x = sex, fill = survived)) +
  geom_bar(color = "black", alpha = 0.75) +
  labs(x = "Sex", y = "Count") +
  scale_fill_discrete(name = "Survived")

# Survival by Socioeconomic Status:
plot_pclass = 
  eda_df %>% 
  ggplot(aes(x = pclass, fill = survived)) +
  geom_bar(color = "black", alpha = 0.75) + 
  labs(x = "Socioeconomic Status", y = "Count") +
  scale_fill_discrete(name = "Survived")

# Survival by Port of Embarkation:
plot_emb = 
  eda_df %>% 
  ggplot(aes(x = embarked, fill = survived)) +
  geom_bar(color = "black", alpha = 0.75) + 
  labs(x = "Port of Embarkation", y = "Count") +
  scale_fill_discrete(name = "Survived")

layout = "
AAABBB
CCCDDD
EEFFGG
"
plot_age + plot_fare + plot_sibsp + plot_parch + plot_sex + 
  plot_pclass + plot_emb + plot_layout(design = layout, guides = "collect")

# Survival of Age vs Fare by SES and Sex
eda_df %>% 
  filter(fare < 100) %>% 
  ggplot(aes(x = age, y = fare, color = survived)) +
  geom_point(alpha = 0.75) + 
  facet_grid(sex ~ pclass) + 
  labs(x = "Age", y = "Fare") +
  scale_color_discrete(name = "Survived")

# Survival of Age vs Fare by Embarkation and Sex
eda_df %>% 
  filter(fare < 100) %>% 
  ggplot(aes(x = age, y = fare, color = survived)) +
  geom_point(alpha = 0.75) + 
  facet_grid(sex ~ embarked) + 
  labs(x = "Age", y = "Fare") +
  scale_color_discrete(name = "Survived")
```

## **Model Training**

```{r models, message = F, warning = F}
ctrl = trainControl(method = "repeatedcv", summaryFunction = twoClassSummary, classProbs = T, number = 10, repeats = 5)

set.seed(37564)
mod_enet = train(survived ~ .,
                 na.action = na.exclude, 
                 data = train_df, 
                 method = "glmnet", 
                 family = "binomial", 
                 metric = "ROC", 
                 tuneGrid = expand.grid(alpha = seq(0, 0.5, length = 6), 
                                        lambda = exp(seq(-4, -8, length = 50))),
                 trControl = ctrl)
tuning_plot_enet = 
  ggplot(mod_enet, highlight = T) + 
  ggtitle("Elastic Net") +
  theme(plot.title = element_text(hjust = 0.5))
mod_enet$bestTune

set.seed(37564)
mod_mars = train(survived ~ ., 
                 na.action = na.exclude, 
                 data = train_df, 
                 method = "earth",
                 tuneGrid = expand.grid(degree = 1:3, nprune = 5:15), 
                 metric = "ROC", 
                 trControl = ctrl)
tuning_plot_mars = 
  ggplot(mod_mars, highlight = T) + 
  ggtitle("MARS") +
  theme(plot.title = element_text(hjust = 0.5))
mod_mars$bestTune

set.seed(37564)
mod_knn = train(survived ~ .,
                na.action = na.exclude, 
                data = train_df, 
                method = "knn",
                metric = "ROC", 
                preProcess = c("center","scale"),
                tuneGrid = data.frame(k = seq(1, 30, by = 1)), 
                trControl = ctrl)
tuning_plot_knn = 
  ggplot(mod_knn, highlight = T) + 
  ggtitle("KNN") +
  theme(plot.title = element_text(hjust = 0.5))
mod_knn$bestTune

set.seed(37564)
mod_boost = train(survived ~ .,
                  na.action = na.exclude,
                  data = train_df,
                  method = "gbm",
                  distribution = "adaboost",
                  tuneGrid = expand.grid(n.trees = c(2000, 3000),
                                         interaction.depth = 4:13,
                                         shrinkage = c(0.003, 0.005, 0.007), 
                                         n.minobsinnode = 1),
                  metric = "ROC",
                  trControl = ctrl,
                  verbose = F)
tuning_plot_boost = 
  ggplot(mod_boost, highlight = T) + 
  ggtitle("Boosting") +
  theme(plot.title = element_text(hjust = 0.5))
mod_boost$bestTune

set.seed(37564)
mod_svm = train(survived ~ .,
                na.action = na.exclude,
                data = train_df,
                preProcess = c("scale", "center"),
                method = "svmRadialSigma",
                tuneGrid = expand.grid(C = exp(seq(-2,3, len = 10)),
                                       sigma = exp(seq(-8,0, len = 10))),
                metric = "ROC",
                trControl = ctrl)
tuning_plot_svm = 
  ggplot(mod_svm, highlight = T) + 
  ggtitle("SVM Radial") +
  theme(plot.title = element_text(hjust = 0.5))
mod_svm$bestTune

layout2 = "
AABB
CCDD
EEEE
"
tuning_plot_knn + tuning_plot_enet + 
  tuning_plot_mars + tuning_plot_svm + 
  tuning_plot_boost + plot_layout(design = layout2)

res = resamples(list(ENET = mod_enet, MARS = mod_mars, KNN = mod_knn, BOOST = mod_boost, SVM = mod_svm))
summary(res)
bwplot(res, metric = "ROC", main = "ROC for Repeated 10-Fold CV Using Various Models")
```

## **Variable Importance**

```{r vip, message = F, warning = F}
set.seed(37564)

vip(mod_boost, 
    method = "permute", 
    train = train_df,
    target = "survived",
    metric = "auc",
    reference_class = c("yes", "no"),
    nsim = 30,
    pred_wrapper = predict,
    geom = "boxplot", 
    all_permutations = T,
    mapping = aes_string(fill = "Variable", alpha = 0.75))

#Check if enet parameters micking importance pattern
coef(mod_enet$finalModel, mod_enet$bestTune$lambda)
```

## **Predictions**

```{r pred, message = F, warning = F}
testna_df = 
  read_csv("./data/test.csv") %>% 
  janitor::clean_names() %>% 
  select(-c(ticket, cabin, name)) %>% 
  left_join(janitor::clean_names(read_csv("./data/titanic_results.csv"))) %>%
  mutate(pclass = as.factor(pclass), 
         sex = as.factor(sex), 
         embarked = as.factor(embarked))

testX = testna_df[,2:8]
test_bag = preProcess(testX, method = "bagImpute")
test_df = predict(test_bag, testX) %>% 
  cbind(testna_df[1], testna_df[9])

pred_knn = predict(mod_knn, newdata = test_df, type = "prob")[,1]
roc_knn = roc(test_df$survived, pred_knn)
plot(roc_knn, legacy.axes = T)

pred_enet = predict(mod_enet, newdata = test_df, type = "prob")[,1]
roc_enet = roc(test_df$survived, pred_enet)
plot(roc_enet, add = T, col = 2)

pred_svm = predict(mod_svm, newdata = test_df, type = "prob")[,1]
roc_svm = roc(test_df$survived, pred_svm)
plot(roc_svm, add = T, col = 3)

pred_mars = predict(mod_mars, newdata = test_df, type = "prob")[,1]
roc_mars = roc(test_df$survived, pred_mars)
plot(roc_mars, add = T, col = 4)

pred_boost = predict(mod_boost, newdata = test_df, type = "prob")[,1]
roc_boost = roc(test_df$survived, pred_boost)

auc = c(roc_knn$auc[1], roc_enet$auc[1], roc_svm$auc[1], roc_mars$auc[1], roc_boost$auc[1])
modelNames = c("KNN","Elastic Net", "SVM", "MARS", "Boosting")
legend("bottomright", legend = paste0(modelNames, ": ", round(auc,3)),
       col = c(1:4, 7), lwd = 2)
plot(roc_boost, add = T, col = 7)
```

## **Boosted RF Model Analysis**

```{r model_analysis}
cm_df = pred_boost %>% 
  as.data.frame() %>% 
  rename("survived" = ".") %>% 
  mutate(survived = as.factor(ifelse(survived >= 0.5, 1, 0)))
  
confusionMatrix(data = cm_df$survived, reference = as.factor(test_df$survived))

explainer_gbm = explain(mod_boost, 
                        label = "gbm",
                        data = train_df[-1],
                        y = as.numeric(train_df$survived == "yes"),
                        verbose = F)

vi_gbm = model_parts(explainer_gbm)

plot(vi_gbm)

pdp_age = model_profile(explainer_gbm,
                        variable = "age",
                        type = "partial")

pdp_fare = model_profile(explainer_gbm,
                         variable = "fare",
                         type = "partial")

plot(pdp_age, pdp_fare)

pb_gbm = predict_parts(explainer_gbm,
                       new_observation = test_df[1,],
                       type = "break_down")

plot(pb_gbm)
```

```{r kaggle comp, include = F}
# Submission for Kaggle Competition:
test_id = testna_df$passenger_id

test_res = 
  pred_boost %>% 
  as.data.frame() %>% 
  mutate(survived = ifelse(pred_boost > 0.5, 0, 1))

submission = 
  cbind(test_id, test_res$survived) %>% 
  as.data.frame() %>% 
  rename(PassengerId = test_pid,
         Survived = V2)

write_csv(submission, "submission.csv")
```

